### ISSUE TITLE
Limit of 11 ACE lines

### ISSUE THREAD

**Issue by elear** [CiscoDevNet/MUD-Manager#8]
The code uses an array, but should instead use a realloc()able pointer.

**Comment by elear** [comment]
Problem occurs with number of manufacturers, number of ACES, and number of ACLs to name a few.

**Comment by elear** [comment]
The real problem here isn't the # of manufacturers (that is a problem) but the number of ACE lines.  To get to a larger # of manufacturers we need to get rid of the manufacturers array in the config.  With addressing, Issue #19 we've begun that by moving VLANs out.  Same with #22 and Local networks.

**Comment by iggy2028** [comment]
When you say "get rid of the manufacturers array", of course using allocated memory is better and that should be done as necessary. But with the comment of "moving VLANs out" I think you have a broader goal. I'm not sure what you're move out. Note that the limits on the number ACL and ACE statements that have been increased only affect what is in memory while the MUD file is processed. The resulting ACL and other policy gets stored in the MongoDB collection and all of the allocated memory should be released with "acllist".

**Comment by elear** [comment]
Sorry- I was thinking of the array in the config file.  I'd like that not to exist.  The manuf_list[] construct is fine internally.
